# spring common setting
spring:
  profiles:
    default: local

--- #local
server:
  port: 18080

spring:
  config:
    activate:
      on-profile: local
  #정적 리소스(HTML, JS, CSS) 바로 적용 설정
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  #타임리프 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

#상수 모음
ebook:
  value:
    pdf:
      dir: C://Users/user/Desktop/
    img:
      dir: src/main/resources/static/img/ebook/


--- #prod
server:
  port: 18080

spring:
  config:
    activate:
      on-profile: prod
  #정적 리소스(HTML, JS, CSS) 바로 적용 설정
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  #타임리프 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

#상수 모음
ebook:
  value:
    pdf:
      dir: /ebook/pdf/
    img:
      dir: /ebook/image/